//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQH_DATN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DQH_DATNEntities : DbContext
    {
        public DQH_DATNEntities()
            : base("name=DQH_DATNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblBinhluan> tblBinhluan { get; set; }
        public virtual DbSet<tblDanhmucSP> tblDanhmucSP { get; set; }
        public virtual DbSet<tblDonhang> tblDonhang { get; set; }
        public virtual DbSet<tblLoaitrangthai> tblLoaitrangthai { get; set; }
        public virtual DbSet<tblNguoidung> tblNguoidung { get; set; }
        public virtual DbSet<tblNhacungcap> tblNhacungcap { get; set; }
        public virtual DbSet<tblPhieunhap> tblPhieunhap { get; set; }
        public virtual DbSet<tblQuyen> tblQuyen { get; set; }
        public virtual DbSet<tblSanpham> tblSanpham { get; set; }
        public virtual DbSet<tblTrangthai> tblTrangthai { get; set; }
        public virtual DbSet<tblChitietdonhang> tblChitietdonhang { get; set; }
        public virtual DbSet<tblChitietphieunhap> tblChitietphieunhap { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int spBinhluan_delete(Nullable<int> pK_iBinhluanID)
        {
            var pK_iBinhluanIDParameter = pK_iBinhluanID.HasValue ?
                new ObjectParameter("PK_iBinhluanID", pK_iBinhluanID) :
                new ObjectParameter("PK_iBinhluanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spBinhluan_delete", pK_iBinhluanIDParameter);
        }
    
        public virtual ObjectResult<spBinhluan_getBySanpham_Result> spBinhluan_getBySanpham(Nullable<int> fK_iSanphamID)
        {
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBinhluan_getBySanpham_Result>("spBinhluan_getBySanpham", fK_iSanphamIDParameter);
        }
    
        public virtual int spBinhluan_insert(string sNoidung, Nullable<System.DateTime> dThoigian, Nullable<int> fK_iNguoidungID, Nullable<int> fK_iSanphamID)
        {
            var sNoidungParameter = sNoidung != null ?
                new ObjectParameter("sNoidung", sNoidung) :
                new ObjectParameter("sNoidung", typeof(string));
    
            var dThoigianParameter = dThoigian.HasValue ?
                new ObjectParameter("dThoigian", dThoigian) :
                new ObjectParameter("dThoigian", typeof(System.DateTime));
    
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(int));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spBinhluan_insert", sNoidungParameter, dThoigianParameter, fK_iNguoidungIDParameter, fK_iSanphamIDParameter);
        }
    
        public virtual int spBinhluan_update(Nullable<int> pK_iBinhluanID, string sNoidung, Nullable<System.DateTime> dThoigian, Nullable<int> fK_iNguoidungID, Nullable<int> fK_iSanphamID)
        {
            var pK_iBinhluanIDParameter = pK_iBinhluanID.HasValue ?
                new ObjectParameter("PK_iBinhluanID", pK_iBinhluanID) :
                new ObjectParameter("PK_iBinhluanID", typeof(int));
    
            var sNoidungParameter = sNoidung != null ?
                new ObjectParameter("sNoidung", sNoidung) :
                new ObjectParameter("sNoidung", typeof(string));
    
            var dThoigianParameter = dThoigian.HasValue ?
                new ObjectParameter("dThoigian", dThoigian) :
                new ObjectParameter("dThoigian", typeof(System.DateTime));
    
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(int));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spBinhluan_update", pK_iBinhluanIDParameter, sNoidungParameter, dThoigianParameter, fK_iNguoidungIDParameter, fK_iSanphamIDParameter);
        }
    
        public virtual int spChitietdonhang_delete(Nullable<int> fK_iDonhangID, Nullable<int> fK_iSanphamID)
        {
            var fK_iDonhangIDParameter = fK_iDonhangID.HasValue ?
                new ObjectParameter("FK_iDonhangID", fK_iDonhangID) :
                new ObjectParameter("FK_iDonhangID", typeof(int));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChitietdonhang_delete", fK_iDonhangIDParameter, fK_iSanphamIDParameter);
        }
    
        public virtual ObjectResult<spChitietdonhang_getByID_Result> spChitietdonhang_getByID(Nullable<int> fK_iDonhangID)
        {
            var fK_iDonhangIDParameter = fK_iDonhangID.HasValue ?
                new ObjectParameter("FK_iDonhangID", fK_iDonhangID) :
                new ObjectParameter("FK_iDonhangID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spChitietdonhang_getByID_Result>("spChitietdonhang_getByID", fK_iDonhangIDParameter);
        }
    
        public virtual int spChitietdonhang_insert(Nullable<int> fK_iDonhangID, Nullable<int> fK_iSanphamID, Nullable<int> iSoluong, Nullable<int> iDongia)
        {
            var fK_iDonhangIDParameter = fK_iDonhangID.HasValue ?
                new ObjectParameter("FK_iDonhangID", fK_iDonhangID) :
                new ObjectParameter("FK_iDonhangID", typeof(int));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(int));
    
            var iSoluongParameter = iSoluong.HasValue ?
                new ObjectParameter("iSoluong", iSoluong) :
                new ObjectParameter("iSoluong", typeof(int));
    
            var iDongiaParameter = iDongia.HasValue ?
                new ObjectParameter("iDongia", iDongia) :
                new ObjectParameter("iDongia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChitietdonhang_insert", fK_iDonhangIDParameter, fK_iSanphamIDParameter, iSoluongParameter, iDongiaParameter);
        }
    
        public virtual int spChitietdonhang_update(Nullable<int> fK_iDonhangID, Nullable<int> fK_iSanphamID, Nullable<int> iSoluong, Nullable<int> iDongia)
        {
            var fK_iDonhangIDParameter = fK_iDonhangID.HasValue ?
                new ObjectParameter("FK_iDonhangID", fK_iDonhangID) :
                new ObjectParameter("FK_iDonhangID", typeof(int));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(int));
    
            var iSoluongParameter = iSoluong.HasValue ?
                new ObjectParameter("iSoluong", iSoluong) :
                new ObjectParameter("iSoluong", typeof(int));
    
            var iDongiaParameter = iDongia.HasValue ?
                new ObjectParameter("iDongia", iDongia) :
                new ObjectParameter("iDongia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChitietdonhang_update", fK_iDonhangIDParameter, fK_iSanphamIDParameter, iSoluongParameter, iDongiaParameter);
        }
    
        public virtual int spChitietphieunhap_delete(Nullable<int> fK_iPhieunhapID, Nullable<int> fK_iSanphamID)
        {
            var fK_iPhieunhapIDParameter = fK_iPhieunhapID.HasValue ?
                new ObjectParameter("FK_iPhieunhapID", fK_iPhieunhapID) :
                new ObjectParameter("FK_iPhieunhapID", typeof(int));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChitietphieunhap_delete", fK_iPhieunhapIDParameter, fK_iSanphamIDParameter);
        }
    
        public virtual ObjectResult<spChitietphieunhap_getByID_Result> spChitietphieunhap_getByID(Nullable<int> fK_iPhieunhapID, Nullable<int> fK_iSanphamID, Nullable<int> iSoluong, Nullable<int> iGianhap, Nullable<int> iGiaban)
        {
            var fK_iPhieunhapIDParameter = fK_iPhieunhapID.HasValue ?
                new ObjectParameter("FK_iPhieunhapID", fK_iPhieunhapID) :
                new ObjectParameter("FK_iPhieunhapID", typeof(int));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(int));
    
            var iSoluongParameter = iSoluong.HasValue ?
                new ObjectParameter("iSoluong", iSoluong) :
                new ObjectParameter("iSoluong", typeof(int));
    
            var iGianhapParameter = iGianhap.HasValue ?
                new ObjectParameter("iGianhap", iGianhap) :
                new ObjectParameter("iGianhap", typeof(int));
    
            var iGiabanParameter = iGiaban.HasValue ?
                new ObjectParameter("iGiaban", iGiaban) :
                new ObjectParameter("iGiaban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spChitietphieunhap_getByID_Result>("spChitietphieunhap_getByID", fK_iPhieunhapIDParameter, fK_iSanphamIDParameter, iSoluongParameter, iGianhapParameter, iGiabanParameter);
        }
    
        public virtual int spChitietphieunhap_insert(Nullable<int> fK_iPhieunhapID, Nullable<int> fK_iSanphamID, Nullable<int> iSoluong, Nullable<int> iGianhap, Nullable<int> iGiaban)
        {
            var fK_iPhieunhapIDParameter = fK_iPhieunhapID.HasValue ?
                new ObjectParameter("FK_iPhieunhapID", fK_iPhieunhapID) :
                new ObjectParameter("FK_iPhieunhapID", typeof(int));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(int));
    
            var iSoluongParameter = iSoluong.HasValue ?
                new ObjectParameter("iSoluong", iSoluong) :
                new ObjectParameter("iSoluong", typeof(int));
    
            var iGianhapParameter = iGianhap.HasValue ?
                new ObjectParameter("iGianhap", iGianhap) :
                new ObjectParameter("iGianhap", typeof(int));
    
            var iGiabanParameter = iGiaban.HasValue ?
                new ObjectParameter("iGiaban", iGiaban) :
                new ObjectParameter("iGiaban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChitietphieunhap_insert", fK_iPhieunhapIDParameter, fK_iSanphamIDParameter, iSoluongParameter, iGianhapParameter, iGiabanParameter);
        }
    
        public virtual int spChitietphieunhap_update(Nullable<int> fK_iPhieunhapID, Nullable<int> fK_iSanphamID, Nullable<int> iSoluong, Nullable<int> iGianhap, Nullable<int> iGiaban)
        {
            var fK_iPhieunhapIDParameter = fK_iPhieunhapID.HasValue ?
                new ObjectParameter("FK_iPhieunhapID", fK_iPhieunhapID) :
                new ObjectParameter("FK_iPhieunhapID", typeof(int));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(int));
    
            var iSoluongParameter = iSoluong.HasValue ?
                new ObjectParameter("iSoluong", iSoluong) :
                new ObjectParameter("iSoluong", typeof(int));
    
            var iGianhapParameter = iGianhap.HasValue ?
                new ObjectParameter("iGianhap", iGianhap) :
                new ObjectParameter("iGianhap", typeof(int));
    
            var iGiabanParameter = iGiaban.HasValue ?
                new ObjectParameter("iGiaban", iGiaban) :
                new ObjectParameter("iGiaban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChitietphieunhap_update", fK_iPhieunhapIDParameter, fK_iSanphamIDParameter, iSoluongParameter, iGianhapParameter, iGiabanParameter);
        }
    
        public virtual ObjectResult<spDanhmuc_getbyID_Result> spDanhmuc_getbyID(Nullable<int> pK_iDanhmucID)
        {
            var pK_iDanhmucIDParameter = pK_iDanhmucID.HasValue ?
                new ObjectParameter("PK_iDanhmucID", pK_iDanhmucID) :
                new ObjectParameter("PK_iDanhmucID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDanhmuc_getbyID_Result>("spDanhmuc_getbyID", pK_iDanhmucIDParameter);
        }
    
        public virtual int spDonhang_delete(Nullable<int> pK_iDonhangID)
        {
            var pK_iDonhangIDParameter = pK_iDonhangID.HasValue ?
                new ObjectParameter("PK_iDonhangID", pK_iDonhangID) :
                new ObjectParameter("PK_iDonhangID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDonhang_delete", pK_iDonhangIDParameter);
        }
    
        public virtual ObjectResult<spDonhang_getByID_Result> spDonhang_getByID(Nullable<int> pK_iDonhangiD)
        {
            var pK_iDonhangiDParameter = pK_iDonhangiD.HasValue ?
                new ObjectParameter("PK_iDonhangiD", pK_iDonhangiD) :
                new ObjectParameter("PK_iDonhangiD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDonhang_getByID_Result>("spDonhang_getByID", pK_iDonhangiDParameter);
        }
    
        public virtual int spDonhang_insert(string sDiachiGiao, string sSDT, Nullable<System.DateTime> dNgaydat, Nullable<int> fK_iNguoidungID, Nullable<int> fK_iTrangthaiID)
        {
            var sDiachiGiaoParameter = sDiachiGiao != null ?
                new ObjectParameter("sDiachiGiao", sDiachiGiao) :
                new ObjectParameter("sDiachiGiao", typeof(string));
    
            var sSDTParameter = sSDT != null ?
                new ObjectParameter("sSDT", sSDT) :
                new ObjectParameter("sSDT", typeof(string));
    
            var dNgaydatParameter = dNgaydat.HasValue ?
                new ObjectParameter("dNgaydat", dNgaydat) :
                new ObjectParameter("dNgaydat", typeof(System.DateTime));
    
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(int));
    
            var fK_iTrangthaiIDParameter = fK_iTrangthaiID.HasValue ?
                new ObjectParameter("FK_iTrangthaiID", fK_iTrangthaiID) :
                new ObjectParameter("FK_iTrangthaiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDonhang_insert", sDiachiGiaoParameter, sSDTParameter, dNgaydatParameter, fK_iNguoidungIDParameter, fK_iTrangthaiIDParameter);
        }
    
        public virtual int spDonhang_update(Nullable<int> pK_iDonhangiD, string sDiachiGiao, string sSDT, Nullable<System.DateTime> dNgaydat, Nullable<int> fK_iNguoidungID, Nullable<int> fK_iTrangthaiID)
        {
            var pK_iDonhangiDParameter = pK_iDonhangiD.HasValue ?
                new ObjectParameter("PK_iDonhangiD", pK_iDonhangiD) :
                new ObjectParameter("PK_iDonhangiD", typeof(int));
    
            var sDiachiGiaoParameter = sDiachiGiao != null ?
                new ObjectParameter("sDiachiGiao", sDiachiGiao) :
                new ObjectParameter("sDiachiGiao", typeof(string));
    
            var sSDTParameter = sSDT != null ?
                new ObjectParameter("sSDT", sSDT) :
                new ObjectParameter("sSDT", typeof(string));
    
            var dNgaydatParameter = dNgaydat.HasValue ?
                new ObjectParameter("dNgaydat", dNgaydat) :
                new ObjectParameter("dNgaydat", typeof(System.DateTime));
    
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(int));
    
            var fK_iTrangthaiIDParameter = fK_iTrangthaiID.HasValue ?
                new ObjectParameter("FK_iTrangthaiID", fK_iTrangthaiID) :
                new ObjectParameter("FK_iTrangthaiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDonhang_update", pK_iDonhangiDParameter, sDiachiGiaoParameter, sSDTParameter, dNgaydatParameter, fK_iNguoidungIDParameter, fK_iTrangthaiIDParameter);
        }
    
        public virtual int spNguoidung_delete(Nullable<int> pK_iNguoidungID)
        {
            var pK_iNguoidungIDParameter = pK_iNguoidungID.HasValue ?
                new ObjectParameter("PK_iNguoidungID", pK_iNguoidungID) :
                new ObjectParameter("PK_iNguoidungID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNguoidung_delete", pK_iNguoidungIDParameter);
        }
    
        public virtual ObjectResult<spNguoidung_getByID_Result> spNguoidung_getByID(Nullable<int> pK_iNguoidungID)
        {
            var pK_iNguoidungIDParameter = pK_iNguoidungID.HasValue ?
                new ObjectParameter("PK_iNguoidungID", pK_iNguoidungID) :
                new ObjectParameter("PK_iNguoidungID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spNguoidung_getByID_Result>("spNguoidung_getByID", pK_iNguoidungIDParameter);
        }
    
        public virtual int spNguoidung_insert(string sTennguoidung, Nullable<System.DateTime> dNgaysinh, Nullable<bool> bGioitinh, string sDiachi, string sSDT, string sTendangnhap, string sMatkhau, Nullable<int> fK_iQuyenID, Nullable<int> fK_iTrangthaiID)
        {
            var sTennguoidungParameter = sTennguoidung != null ?
                new ObjectParameter("sTennguoidung", sTennguoidung) :
                new ObjectParameter("sTennguoidung", typeof(string));
    
            var dNgaysinhParameter = dNgaysinh.HasValue ?
                new ObjectParameter("dNgaysinh", dNgaysinh) :
                new ObjectParameter("dNgaysinh", typeof(System.DateTime));
    
            var bGioitinhParameter = bGioitinh.HasValue ?
                new ObjectParameter("bGioitinh", bGioitinh) :
                new ObjectParameter("bGioitinh", typeof(bool));
    
            var sDiachiParameter = sDiachi != null ?
                new ObjectParameter("sDiachi", sDiachi) :
                new ObjectParameter("sDiachi", typeof(string));
    
            var sSDTParameter = sSDT != null ?
                new ObjectParameter("sSDT", sSDT) :
                new ObjectParameter("sSDT", typeof(string));
    
            var sTendangnhapParameter = sTendangnhap != null ?
                new ObjectParameter("sTendangnhap", sTendangnhap) :
                new ObjectParameter("sTendangnhap", typeof(string));
    
            var sMatkhauParameter = sMatkhau != null ?
                new ObjectParameter("sMatkhau", sMatkhau) :
                new ObjectParameter("sMatkhau", typeof(string));
    
            var fK_iQuyenIDParameter = fK_iQuyenID.HasValue ?
                new ObjectParameter("FK_iQuyenID", fK_iQuyenID) :
                new ObjectParameter("FK_iQuyenID", typeof(int));
    
            var fK_iTrangthaiIDParameter = fK_iTrangthaiID.HasValue ?
                new ObjectParameter("FK_iTrangthaiID", fK_iTrangthaiID) :
                new ObjectParameter("FK_iTrangthaiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNguoidung_insert", sTennguoidungParameter, dNgaysinhParameter, bGioitinhParameter, sDiachiParameter, sSDTParameter, sTendangnhapParameter, sMatkhauParameter, fK_iQuyenIDParameter, fK_iTrangthaiIDParameter);
        }
    
        public virtual ObjectResult<spNguoidung_login_Result> spNguoidung_login(string sTendangnhap, string sMatkhau)
        {
            var sTendangnhapParameter = sTendangnhap != null ?
                new ObjectParameter("sTendangnhap", sTendangnhap) :
                new ObjectParameter("sTendangnhap", typeof(string));
    
            var sMatkhauParameter = sMatkhau != null ?
                new ObjectParameter("sMatkhau", sMatkhau) :
                new ObjectParameter("sMatkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spNguoidung_login_Result>("spNguoidung_login", sTendangnhapParameter, sMatkhauParameter);
        }
    
        public virtual int spNguoidung_update(Nullable<int> pK_iNguoidungID, string sTennguoidung, Nullable<System.DateTime> dNgaysinh, Nullable<bool> bGioitinh, string sDiachi, string sSDT, string sTendangnhap, string sMatkhau, Nullable<int> fK_iQuyenID, Nullable<int> fK_iTrangthaiID)
        {
            var pK_iNguoidungIDParameter = pK_iNguoidungID.HasValue ?
                new ObjectParameter("PK_iNguoidungID", pK_iNguoidungID) :
                new ObjectParameter("PK_iNguoidungID", typeof(int));
    
            var sTennguoidungParameter = sTennguoidung != null ?
                new ObjectParameter("sTennguoidung", sTennguoidung) :
                new ObjectParameter("sTennguoidung", typeof(string));
    
            var dNgaysinhParameter = dNgaysinh.HasValue ?
                new ObjectParameter("dNgaysinh", dNgaysinh) :
                new ObjectParameter("dNgaysinh", typeof(System.DateTime));
    
            var bGioitinhParameter = bGioitinh.HasValue ?
                new ObjectParameter("bGioitinh", bGioitinh) :
                new ObjectParameter("bGioitinh", typeof(bool));
    
            var sDiachiParameter = sDiachi != null ?
                new ObjectParameter("sDiachi", sDiachi) :
                new ObjectParameter("sDiachi", typeof(string));
    
            var sSDTParameter = sSDT != null ?
                new ObjectParameter("sSDT", sSDT) :
                new ObjectParameter("sSDT", typeof(string));
    
            var sTendangnhapParameter = sTendangnhap != null ?
                new ObjectParameter("sTendangnhap", sTendangnhap) :
                new ObjectParameter("sTendangnhap", typeof(string));
    
            var sMatkhauParameter = sMatkhau != null ?
                new ObjectParameter("sMatkhau", sMatkhau) :
                new ObjectParameter("sMatkhau", typeof(string));
    
            var fK_iQuyenIDParameter = fK_iQuyenID.HasValue ?
                new ObjectParameter("FK_iQuyenID", fK_iQuyenID) :
                new ObjectParameter("FK_iQuyenID", typeof(int));
    
            var fK_iTrangthaiIDParameter = fK_iTrangthaiID.HasValue ?
                new ObjectParameter("FK_iTrangthaiID", fK_iTrangthaiID) :
                new ObjectParameter("FK_iTrangthaiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNguoidung_update", pK_iNguoidungIDParameter, sTennguoidungParameter, dNgaysinhParameter, bGioitinhParameter, sDiachiParameter, sSDTParameter, sTendangnhapParameter, sMatkhauParameter, fK_iQuyenIDParameter, fK_iTrangthaiIDParameter);
        }
    
        public virtual int spNhacungcap_delete(Nullable<int> pK_iNCCID)
        {
            var pK_iNCCIDParameter = pK_iNCCID.HasValue ?
                new ObjectParameter("PK_iNCCID", pK_iNCCID) :
                new ObjectParameter("PK_iNCCID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNhacungcap_delete", pK_iNCCIDParameter);
        }
    
        public virtual ObjectResult<spNhacungcap_getByID_Result> spNhacungcap_getByID(Nullable<int> pK_iNCCID)
        {
            var pK_iNCCIDParameter = pK_iNCCID.HasValue ?
                new ObjectParameter("PK_iNCCID", pK_iNCCID) :
                new ObjectParameter("PK_iNCCID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spNhacungcap_getByID_Result>("spNhacungcap_getByID", pK_iNCCIDParameter);
        }
    
        public virtual int spNhacungcap_insert(string sTenNCC, string sDiachi, string sSDT)
        {
            var sTenNCCParameter = sTenNCC != null ?
                new ObjectParameter("sTenNCC", sTenNCC) :
                new ObjectParameter("sTenNCC", typeof(string));
    
            var sDiachiParameter = sDiachi != null ?
                new ObjectParameter("sDiachi", sDiachi) :
                new ObjectParameter("sDiachi", typeof(string));
    
            var sSDTParameter = sSDT != null ?
                new ObjectParameter("sSDT", sSDT) :
                new ObjectParameter("sSDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNhacungcap_insert", sTenNCCParameter, sDiachiParameter, sSDTParameter);
        }
    
        public virtual int spNhacungcap_update(Nullable<int> pK_iNCCID, string sTenNCC, string sDiachi, string sSDT)
        {
            var pK_iNCCIDParameter = pK_iNCCID.HasValue ?
                new ObjectParameter("PK_iNCCID", pK_iNCCID) :
                new ObjectParameter("PK_iNCCID", typeof(int));
    
            var sTenNCCParameter = sTenNCC != null ?
                new ObjectParameter("sTenNCC", sTenNCC) :
                new ObjectParameter("sTenNCC", typeof(string));
    
            var sDiachiParameter = sDiachi != null ?
                new ObjectParameter("sDiachi", sDiachi) :
                new ObjectParameter("sDiachi", typeof(string));
    
            var sSDTParameter = sSDT != null ?
                new ObjectParameter("sSDT", sSDT) :
                new ObjectParameter("sSDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNhacungcap_update", pK_iNCCIDParameter, sTenNCCParameter, sDiachiParameter, sSDTParameter);
        }
    
        public virtual int spSanpham_delete(Nullable<int> pK_iSanphamID)
        {
            var pK_iSanphamIDParameter = pK_iSanphamID.HasValue ?
                new ObjectParameter("PK_iSanphamID", pK_iSanphamID) :
                new ObjectParameter("PK_iSanphamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSanpham_delete", pK_iSanphamIDParameter);
        }
    
        public virtual ObjectResult<spSanpham_getbyDanhmuc_Result> spSanpham_getbyDanhmuc(Nullable<int> fK_iDanhmucID)
        {
            var fK_iDanhmucIDParameter = fK_iDanhmucID.HasValue ?
                new ObjectParameter("FK_iDanhmucID", fK_iDanhmucID) :
                new ObjectParameter("FK_iDanhmucID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSanpham_getbyDanhmuc_Result>("spSanpham_getbyDanhmuc", fK_iDanhmucIDParameter);
        }
    
        public virtual ObjectResult<spSanpham_GetbyID_Result> spSanpham_GetbyID(Nullable<int> pK_iSanphamID)
        {
            var pK_iSanphamIDParameter = pK_iSanphamID.HasValue ?
                new ObjectParameter("PK_iSanphamID", pK_iSanphamID) :
                new ObjectParameter("PK_iSanphamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSanpham_GetbyID_Result>("spSanpham_GetbyID", pK_iSanphamIDParameter);
        }
    
        public virtual int spSanpham_Update(Nullable<int> pK_iSanphamID, string sTenSP, string sHinhanh, string sMota, Nullable<int> iSoluong, string sDonvi, Nullable<int> iDongia, Nullable<int> fK_iDanhmucID, Nullable<int> fK_iNCCID)
        {
            var pK_iSanphamIDParameter = pK_iSanphamID.HasValue ?
                new ObjectParameter("PK_iSanphamID", pK_iSanphamID) :
                new ObjectParameter("PK_iSanphamID", typeof(int));
    
            var sTenSPParameter = sTenSP != null ?
                new ObjectParameter("sTenSP", sTenSP) :
                new ObjectParameter("sTenSP", typeof(string));
    
            var sHinhanhParameter = sHinhanh != null ?
                new ObjectParameter("sHinhanh", sHinhanh) :
                new ObjectParameter("sHinhanh", typeof(string));
    
            var sMotaParameter = sMota != null ?
                new ObjectParameter("sMota", sMota) :
                new ObjectParameter("sMota", typeof(string));
    
            var iSoluongParameter = iSoluong.HasValue ?
                new ObjectParameter("iSoluong", iSoluong) :
                new ObjectParameter("iSoluong", typeof(int));
    
            var sDonviParameter = sDonvi != null ?
                new ObjectParameter("sDonvi", sDonvi) :
                new ObjectParameter("sDonvi", typeof(string));
    
            var iDongiaParameter = iDongia.HasValue ?
                new ObjectParameter("iDongia", iDongia) :
                new ObjectParameter("iDongia", typeof(int));
    
            var fK_iDanhmucIDParameter = fK_iDanhmucID.HasValue ?
                new ObjectParameter("FK_iDanhmucID", fK_iDanhmucID) :
                new ObjectParameter("FK_iDanhmucID", typeof(int));
    
            var fK_iNCCIDParameter = fK_iNCCID.HasValue ?
                new ObjectParameter("FK_iNCCID", fK_iNCCID) :
                new ObjectParameter("FK_iNCCID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSanpham_Update", pK_iSanphamIDParameter, sTenSPParameter, sHinhanhParameter, sMotaParameter, iSoluongParameter, sDonviParameter, iDongiaParameter, fK_iDanhmucIDParameter, fK_iNCCIDParameter);
        }
    }
}
