//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQH_DATN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBinhluan
    {
        public int PK_iBinhluanID { get; set; }
        public string sNoidung { get; set; }
        public System.DateTime dThoigian { get; set; }
        public int FK_iNguoidungID { get; set; }
        public int FK_iSanphamID { get; set; }
    
        public virtual tblNguoidung tblNguoidung { get; set; }
        public virtual tblSanpham tblSanpham { get; set; }
    }
}
