//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQH_DATN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChitietphieunhap
    {
        public int FK_iPhieunhapID { get; set; }
        public int FK_iSanphamID { get; set; }
        public int iSoluong { get; set; }
        public int iGianhap { get; set; }
        public int iGiaban { get; set; }
    
        public virtual tblPhieunhap tblPhieunhap { get; set; }
        public virtual tblSanpham tblSanpham { get; set; }
    }
}
