//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQH_DATN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDonhang()
        {
            this.tblChitietdonhang = new HashSet<tblChitietdonhang>();
        }
    
        public int PK_iDonhangID { get; set; }
        public string sDiachiGiao { get; set; }
        public string sSDT { get; set; }
        public System.DateTime dNgaydat { get; set; }
        public int FK_iNguoidungID { get; set; }
        public int FK_iTrangthaiID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChitietdonhang> tblChitietdonhang { get; set; }
        public virtual tblNguoidung tblNguoidung { get; set; }
        public virtual tblTrangthai tblTrangthai { get; set; }
    }
}
