//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQH_DATN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoaitrangthai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLoaitrangthai()
        {
            this.tblTrangthai = new HashSet<tblTrangthai>();
        }
    
        public int PK_iLoaiTTID { get; set; }
        public string sLoaiTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrangthai> tblTrangthai { get; set; }
    }
}
