//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQH_DATN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNguoidung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNguoidung()
        {
            this.tblBinhluan = new HashSet<tblBinhluan>();
            this.tblDonhang = new HashSet<tblDonhang>();
            this.tblPhieunhap = new HashSet<tblPhieunhap>();
        }
    
        public int PK_iNguoidungID { get; set; }
        public string sTennguoidung { get; set; }
        public System.DateTime dNgaysinh { get; set; }
        public bool bGioitinh { get; set; }
        public string sDiachi { get; set; }
        public string sSDT { get; set; }
        public string sTendangnhap { get; set; }
        public string sMatkhau { get; set; }
        public int FK_iQuyenID { get; set; }
        public int FK_iTrangthaiID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBinhluan> tblBinhluan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDonhang> tblDonhang { get; set; }
        public virtual tblQuyen tblQuyen { get; set; }
        public virtual tblTrangthai tblTrangthai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhieunhap> tblPhieunhap { get; set; }
    }
}
