//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQH_DATN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhieunhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPhieunhap()
        {
            this.tblChitietphieunhap = new HashSet<tblChitietphieunhap>();
        }
    
        public int PK_iPhieunhapID { get; set; }
        public System.DateTime dNgaynhap { get; set; }
        public string sGhichu { get; set; }
        public int FK_iNCCID { get; set; }
        public int FK_iNguoidung { get; set; }
        public int FK_iTrangthaiID { get; set; }
    
        public virtual tblNguoidung tblNguoidung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChitietphieunhap> tblChitietphieunhap { get; set; }
        public virtual tblTrangthai tblTrangthai { get; set; }
    }
}
