//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQH_DATN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrangthai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTrangthai()
        {
            this.tblDonhang = new HashSet<tblDonhang>();
            this.tblNguoidung = new HashSet<tblNguoidung>();
            this.tblPhieunhap = new HashSet<tblPhieunhap>();
        }
    
        public int PK_iTrangthaiID { get; set; }
        public string sTrangthai { get; set; }
        public int FK_iLoaiTTID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDonhang> tblDonhang { get; set; }
        public virtual tblLoaitrangthai tblLoaitrangthai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNguoidung> tblNguoidung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhieunhap> tblPhieunhap { get; set; }
    }
}
